name: flutter_user
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.1.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  firebase_messaging: ^15.0.4
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4
  google_maps_flutter: ^2.5.0
  geolocator: ^12.0.0
  location: ^7.0.0
  audioplayers: ^6.4.0
  url_launcher: ^6.1.14
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.0.0
  # contacts_service: ^0.6.3
  share_plus: ^10.0.0
  connectivity_plus: ^6.0.5
  package_info_plus: ^8.0.2
  vector_math: ^2.1.4
  webview_flutter: ^4.2.4
  path_provider: ^2.1.1
  flutter_inappwebview: ^6.0.0
  uuid: ^4.5.1
  device_info_plus: ^10.1.2
  pinput: ^5.0.0
  intl: ^0.19.0
  animated_text_kit: ^4.2.2
  flutter_map: ^6.1.0
  geocoding: ^3.0.0
  flutter_google_places_sdk: ^0.3.7
  intl_phone_field:
    git:
      url: https://github.com/armandohackcode/intl_phone_field.git
      ref: developer
  flutter_svg: ^2.0.10+1
  provider: ^6.1.5
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.5
  animate_do: ^3.3.4
  carousel_slider: ^5.0.0
  just_audio: ^0.9.40
  record: ^4.4.3
  dio: ^5.7.0
  # device_installed_apps: ^1.0.1
  # flutter_foreground_task: ^8.10.4
  audio_waveforms: ^1.0.5
  photo_view: ^0.15.0
  image: ^4.3.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_tts: ^4.2.2
  lottie: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/map_style_black.json
    - assets/dark.json

  
