// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA720_rprM6yEPQ82S_ExlXC190rJlPrb4',
    appId: '1:564081173286:web:22e84c118c00ac086357e7',
    messagingSenderId: '564081173286',
    projectId: 'de-abril-6fe0f',
    authDomain: 'de-abril-6fe0f.firebaseapp.com',
    databaseURL: 'https://de-abril-6fe0f-default-rtdb.firebaseio.com',
    storageBucket: 'de-abril-6fe0f.appspot.com',
    measurementId: 'G-CHWVKJ46NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzXL81MLZZQM8L012SnMTUQiUeBTvqRHg',
    appId: '1:564081173286:android:89c302ecdde8d0dd6357e7',
    messagingSenderId: '564081173286',
    projectId: 'de-abril-6fe0f',
    databaseURL: 'https://de-abril-6fe0f-default-rtdb.firebaseio.com',
    storageBucket: 'de-abril-6fe0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWynHB5WHE26pHBfVBuBQUdEO3ZY4Z7Tk',
    appId: '1:564081173286:ios:d5c5f94af9117ccb6357e7',
    messagingSenderId: '564081173286',
    projectId: 'de-abril-6fe0f',
    databaseURL: 'https://de-abril-6fe0f-default-rtdb.firebaseio.com',
    storageBucket: 'de-abril-6fe0f.firebasestorage.app',
    androidClientId: '564081173286-6kacu7h1213bhj8ovqdd0qbnpt6fh4ip.apps.googleusercontent.com',
    iosClientId: '564081173286-e1m534db50sk6g9n701q5p4om181nnu2.apps.googleusercontent.com',
    iosBundleId: 'com.radiomovildeabriluser.userapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWynHB5WHE26pHBfVBuBQUdEO3ZY4Z7Tk',
    appId: '1:564081173286:ios:61d2c24db44754616357e7',
    messagingSenderId: '564081173286',
    projectId: 'de-abril-6fe0f',
    databaseURL: 'https://de-abril-6fe0f-default-rtdb.firebaseio.com',
    storageBucket: 'de-abril-6fe0f.appspot.com',
    androidClientId: '564081173286-gkk4meqel00b3hdfokqbkq0l9lvroca2.apps.googleusercontent.com',
    iosClientId: '564081173286-1slcjlovi4icmum9ntjl4p6th2aveeo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA720_rprM6yEPQ82S_ExlXC190rJlPrb4',
    appId: '1:564081173286:web:22e84c118c00ac086357e7',
    messagingSenderId: '564081173286',
    projectId: 'de-abril-6fe0f',
    authDomain: 'de-abril-6fe0f.firebaseapp.com',
    databaseURL: 'https://de-abril-6fe0f-default-rtdb.firebaseio.com',
    storageBucket: 'de-abril-6fe0f.appspot.com',
    measurementId: 'G-CHWVKJ46NR',
  );
}